create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  subscription_status text not null default 'free' check (subscription_status in ('free', 'premium')),
  created_at timestamptz not null default now()
);

create table if not exists public.reading_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id text not null,
  chapter_id text,
  current_position jsonb not null default '{}'::jsonb,
  progress_percent integer not null default 0 check (progress_percent >= 0 and progress_percent <= 100),
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, book_id)
);

create table if not exists public.user_dictionary (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lexical_entry_id text not null,
  word text not null,
  translation text not null,
  contextual_translation text,
  transcription text,
  part_of_speech text,
  book_id text,
  chapter_id text,
  contexts jsonb not null default '[]'::jsonb,
  progress jsonb not null default '{}'::jsonb,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  unique (user_id, lexical_entry_id)
);

create table if not exists public.reading_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade unique,
  font text not null default 'Literata',
  font_size integer not null default 20,
  line_height numeric not null default 1.55,
  theme text not null default 'cream',
  text_align text not null default 'left',
  text_width integer not null default 720,
  accented_reading boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.reading_sessions (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id text not null,
  chapter_id text,
  duration_seconds integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.reading_progress enable row level security;
alter table public.user_dictionary enable row level security;
alter table public.reading_settings enable row level security;
alter table public.reading_sessions enable row level security;

create policy "profiles are owned by user" on public.profiles
  for all using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "reading progress is owned by user" on public.reading_progress
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "dictionary is owned by user" on public.user_dictionary
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "reading settings are owned by user" on public.reading_settings
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "reading sessions are owned by user" on public.reading_sessions
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
